version: '2.2'
services:
  db_postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: my_db
      POSTGRES_PASSWORD: my_db
  my_service:
    build: ../
    image: my_service
    container_name: my_service
    tty: true
    stdin_open: true
    volumes:
      - ./data/my_service:/config
    ports:
      - 8080:8080
    environment:
      PROFILE: test
    links:
      - db_postgres
    depends_on:
      - db_postgres