name: api-rest
on: [push]
jobs:
  api-rest:
    name: api-rest runner
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Clean - Run Unit Test - Package
        run: mvn clean package
      - name: Testing 
        run: sh functional-test/run-test.sh
      - name: JUnit Report Annotations
        uses: ashley-taylor/junit-report-annotations-action@1.3
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cucumber Report Annotations
        if: always()
        uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
            access-token: ${{ secrets.GITHUB_TOKEN }}
            path: "functional-test/target/CucumberReports/*cucumber.json"
      - name: Send email
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has the status ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has the status ${{ job.status }}
          # comma-separated string, send email to
          to: pao.duq_17@hotmail.com
          # from email name
          from: GitHub Runner            
      - name: Microsoft Teams Notification
        uses: toko-bifrost/ms-teams-deploy-card@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          webhook-uri: ${{ secrets.MSTEAMS_WEBHOOK }}
          custom-facts: |
            - name: Custom Fact Name 1
              value: Custom Fact Value 1
            - name: Pull Request
              value: "http://example.com/${{ github.run_id }}"
          custom-actions: |
            - text: View PR
              url: "http://valid.uri.com"
            - text: View CI
              url: "http://example.com/${{ github.run_id }}"
