name: api-rest
on: [push]
jobs:
  api-rest:
    name: api-rest runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Clean - Run Unit Test - Package
        run: mvn clean package
      - name: Testing 
        run: sh functional-test/run-test.sh
      - name: Generate Report
        if: always()
        uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
            path: "functional-test/target/CucumberReports/*cucumber.json"
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: pao.duq_17@hotmail.com
          # from email name
          from: GitHub Runner            
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          raw: >-
            {
              "@type": "MessageCard",
              "@context": "http://schema.org/extensions",
              "title": "No ${variables} avaliable in here"
            }          
