name: api-rest
on: [push]
jobs:
  api-rest:
    name: api-rest runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: mvn clean package
      - run: sh functional-test/run-test.sh
