name: api-rest
on: [push]
jobs:
  api-rest:
    name: api-rest runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Clean - Run Unit Test - Package
        run: mvn clean package
      - name: Testing 
        run: sh functional-test/run-test.sh
      - name: Generate Report
        uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
            path: "functional-test/target/CucumberReports/*cucumber.json"
